type Job {
    id: ID!
    companyId: ID
    jobTitle: String
    description: String
    location: String
    experienceRequired: Int
    skillsRequired: String
    educationRequired: String
    salaryRange: String
    createdAt: String
    updatedAt: String
  }

  # Entrada para crear o actualizar un trabajo
  input CreateJobInput {
    userId: String
    jobTitle: String
    description: String
    location: String
    experienceRequired: Int
    skillsRequired: String
    educationRequired: String
    salaryRange: String
    status: Boolean
  }

  # Definición de Queries
  type Query {
    getAllJobs: [Job]
    getJobById(id: ID!): Job
  }

  # Definición de Mutations
  type Mutation {
    createJob(input: CreateJobInput): Job
    updateJob(id: ID!, input: CreateJobInput): Job
    deleteJob(id: ID!): Boolean
  }